project:
  type: website
  output-dir: docs
  
website:
  title: "Fay Nguyen"
  navbar:
    background: primary
    search: true
    left:
      - file: index.qmd
        text: "Home"
      - sidebar:projects
    right:
      - icon: github
        href: https://github.com/FayNguyen03
  sidebar:
    - id: projects
      title: "Projects"
      contents:
        - map.qmd
        - simulation.qmd
        - string_regex.qmd
        - museums.qmd
        - sql_practice.qmd
      
  page-footer:
    left: |
      &copy; Khanh Tra Nguyen Tran, 2024<br>
      All content licensed under ![](https://static.thenounproject.com/png/70967-200.png){height=20px} ([CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/))
    right: |
      Site built with [Quarto](https://quarto.org/)

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: source