project:
  type: website
  output-dir: docs
  
website:
  title: "Fay Nguyen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: MSCS 264 Projects
        href: projects.qmd
      - text: Map
        href: map.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/faynguyen03/
      - icon: github
        href: https://github.com/FayNguyen03
      - icon: laptop
        href: https://faynguyen03.github.io/
      
  page-footer:
    left: |
      &copy; Khanh Tra Nguyen Tran, 2024<br>
      All content licensed under ![](https://static.thenounproject.com/png/70967-200.png){height=20px} ([CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/))
    right: |
      Site built with [Quarto](https://quarto.org/)

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: source